### ISSUE TITLE
Use local phantomjs

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/invoiceninja_ynh#10]
https://invoice-system.readthedocs.io/en/latest/configure.html#phantomjs 

https://github.com/YunoHost-Apps/invoiceninja_ynh/blob/2ca5ba836e5bd22c034e40b64f3c361e74038b5f/sources/extra_files/app/.env#L28

**Comment by rndmh3ro** [comment]
https://github.com/YunoHost-Apps/invoiceninja_ynh/pull/11
