### ISSUE TITLE
New version available V5.X

### ISSUE THREAD

**Issue by KvL159** [YunoHost-Apps/invoiceninja_ynh#12]
Invoiceninja V2 (V5.X) is now available : https://github.com/invoiceninja/invoiceninja/releases

It seems a complete rewrite of invoiceninja and we need to use the migration tool :
https://invoiceninja.github.io/selfhost.html#migrating-from-v4

Any plan to upgrade and migrate to the new version for this package ?

Thank you  !

**Comment by rndmh3ro** [comment]
Hi @KvL159,

> Any plan to upgrade and migrate to the new version for this package ?

Yes, I'd like to do that.

Roadmap I just thought up:
* rename this repo to invoiceninja_legacy as the official app does (https://forum.invoiceninja.com/t/the-invoice-ninja-v5-beta-is-now-available/4066)
* create a new repo with v5
* ???
* profit

**Comment by KvL159** [comment]
Hi @rndmh3ro 

Sounds good !

**Comment by rndmh3ro** [comment]
FYI: I started working on it.
Installation worked flawlessly without major changes. Now the nginx-config is giving me some problems.

**Comment by rndmh3ro** [comment]
Here's the alpha-version: https://github.com/YunoHost-Apps/invoiceninja5_ynh

Please expect several things not working:

* you have to run setup because the `env` is not migrated to v5 yet
* migration from v4
* installation into a sub-directory
* sending mails

**Comment by KvL159** [comment]
Awesome @rndmh3ro it's great news!

I'll try to setup on a test server soon
Thank you very much !!! :sunglasses:

**Comment by rndmh3ro** [comment]
Just tested migration with version 5.0.25. migration still not working for me.

**Comment by rndmh3ro** [comment]
some progress:
* migration can be started but does not seem to work yet.
* setup is almost unattended
* following upstream closely.

**Comment by rndmh3ro** [comment]
Version 5 exists for some time here: https://github.com/YunoHost-Apps/invoiceninja5_ynh
