### ISSUE TITLE
invoice ninja API does not work

### ISSUE THREAD

**Issue by mstyp** [YunoHost-Apps/invoiceninja_ynh#31]
When I try to use the API for [invoice ninja](https://www.invoiceninja.com/api-documentation/) by running the command:
```
curl -k -X GET https://yunohost.local/ninja/api/v1/clients -H "X-Ninja-Token: blerpderptokenderp"
```

I get the following response:

```
<html>
<head><title>302 Found</title><script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

This is not what I was expecting. I am assuming that yunohost is getting in the way here somehow, but I am not sure what to do to access the invoice ninja api.

**Comment by rndmh3ro** [comment]
Please see here: https://forum.yunohost.org/t/new-app-invoice-ninja/11168/11

If you still have problems after following this, please tell them in the forums, thanks!
